// TODO: Replace with generated Firebase options
// Run: flutterfire configure --project=YOUR_PROJECT_ID
// This file will be auto-generated by `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7dsWYCn8FmEriW2K_YcDIBN4NdBV2cc',
    appId: '1:260143067060:web:069b0bb74f005d09cacce1',
    messagingSenderId: '260143067060',
    projectId: 'pcb-operations-hub',
    authDomain: 'pcb-operations-hub.firebaseapp.com',
    storageBucket: 'pcb-operations-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAetFaSYnFvJPjZpNOp6HtiTKo7JOcP8',
    appId: '1:260143067060:android:9d8908e5cfaefcedcacce1',
    messagingSenderId: '260143067060',
    projectId: 'pcb-operations-hub',
    storageBucket: 'pcb-operations-hub.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT.appspot.com',
    iosBundleId: 'com.prakashcoach.operations',
  );
}
